// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdFBkZpr6hNxk-HinY3clz_ZlRf4o8sb8',
    appId: '1:540988427119:web:df173814fb4d0f6028b69a',
    messagingSenderId: '540988427119',
    projectId: 'crudtotarial',
    authDomain: 'crudtotarial.firebaseapp.com',
    storageBucket: 'crudtotarial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEjVZ3HB5qrQX2FFjSTAsRA3h2wk6z6OQ',
    appId: '1:540988427119:android:6e0469783b417ded28b69a',
    messagingSenderId: '540988427119',
    projectId: 'crudtotarial',
    storageBucket: 'crudtotarial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9XJUuPMFh3vrgxgtZPyUjeJgvIZMq5c',
    appId: '1:540988427119:ios:3d97343a38ae048c28b69a',
    messagingSenderId: '540988427119',
    projectId: 'crudtotarial',
    storageBucket: 'crudtotarial.appspot.com',
    iosBundleId: 'com.example.vize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9XJUuPMFh3vrgxgtZPyUjeJgvIZMq5c',
    appId: '1:540988427119:ios:ddbeb45aee8a053c28b69a',
    messagingSenderId: '540988427119',
    projectId: 'crudtotarial',
    storageBucket: 'crudtotarial.appspot.com',
    iosBundleId: 'com.example.vize.RunnerTests',
  );
}
